apiVersion: v1
kind: Service
metadata:
  name: brightweb-service
spec:
  selector:
    app: brightweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
  
